### ISSUE TITLE
filter not working

### ISSUE THREAD

**Issue by bVess12** [gottadiveintopython/asynckivy#42]
First, this library is a lifesaver. I was having to write all async code for my application in the "traditional" way with callbacks and it was a nightmare to scale.  I've since changed everything over to use this library.

I'm now trying to await a progress bar reaching a value of 100 after it fills up over time.  You have an example listed on the main page on how to add a filter with a lambda function.  Neither this example nor my attempt work.  Both just result in this error:

TypeError: __init__() got an unexpected keyword argument 'filter'

Original example:
    # wait until 'button.x' becomes greater than 100
    if button.x <= 100:
        __, x = await ak.event(button, 'x', filter=lambda __, x: x>100)
        print(f'button.x is now {x}')

My code:
#wait until the progress bar's value is at least 100
await ak.event(pBar, 'value', filter=lambda __, v: v >= 100)

Am I missing something obvious?

**Comment by gottadiveintopython** [comment]
I'm glad to hear you are using this library since I don't receive many feedbacks.

Regarding the issue, it sounds like you are doing something like this:

```python
some_widget = SomeWidget(..., filter=...)
```

somewhere in your code, which is likely the cause of the error. But since you didn't post a minimal runnable code that re-produce the issue, I cannot investigate it. It's recommended to post a minimal runnable code when you asking for help.

Also, use triple backticks when you post code so that the code below

~~~text
```python
if button.x <= 100:
    __, x = await ak.event(button, 'x', filter=lambda __, x: x>100)
    print(f'button.x is now {x}')
```
~~~

will be rendered:

```python
if button.x <= 100:
    __, x = await ak.event(button, 'x', filter=lambda __, x: x>100)
    print(f'button.x is now {x}')
```
